from __future__ import annotations

from pathlib import Path

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
DEFAULT_SERVICE_URL = f"http://{DEFAULT_HOST}:{DEFAULT_PORT}"
DEFAULT_POLL_INTERVAL = 3
DEFAULT_HEARTBEAT_INTERVAL = 10
DEFAULT_MAX_FILE_SIZE = 5 * 1024 * 1024
TASK_TIMEOUT_SECONDS = 30
CLIENT_STORAGE_DIR = Path(".client_storage")
